### ISSUE TITLE
'require' default should be false not true

### ISSUE THREAD

**Issue by ekilzen** [aspida/openapi2aspida#138]
## Description

The default requirement of body value and parameter should be false when requirement of entire object is true.  

## Environment

- **Package version:**
  
  `v0.16.3`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `14.16.1`
- **npm version:**
  
  `7.9.0`

**Comment by LumaKernel** [comment]
As I stated in https://github.com/aspida/openapi2aspida/pull/139,
The problems are
  1. JSON Schema conversion is incorrect for object parameters.
  2. Some json schema level properties should be optional by default.

**Comment by ippeiukai** [comment]
This is a show-stopper for us as the OpenAPI library we use on the server side does not output `"required": false` in the schema.json.
Manually patching the generated type def files post-generation for now, but this is not sustainable :(

**Comment by LumaKernel** [comment]
Hello, we decided to stop current behavior and follow the specs.
