### ISSUE TITLE
Syntax error in component type name

### ISSUE THREAD

**Issue by mosmos21** [aspida/openapi2aspida#142]
## Description
Typescript does not allow type names to start with numbers, so the type generated when defining a component like the example will have a syntax error.

```yaml
title: '401'
type: object
properties:
  error:
    type: string
```

```typescript
export type 401 = {
  error: string
}
```

## Environment

- **Package version:**
  
  `v0.16.3`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `14.16.1`
- **npm version:**
  
  `7.12.0`

**Comment by solufa** [comment]
Thanks for your posting.
I fixed this.
