### ISSUE TITLE
items: { nullable: true }としたarrayが正しく変換されない

### ISSUE THREAD

**Issue by ID157** [aspida/openapi2aspida#159]
## Description
（OSSにコミットをするのに慣れていないため、拙い所が多々あるかもしれませんがご了承いただけますと幸いです）

次のような`nullable:true`なitemsを持つarrayの型が、正しく変換されない。
```
openapi: 3.0.0
info:
  title: example
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /example:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
      operationId: get-example
components:
  schemas:
    Example:
      title: Example
      type: array
      description: ''
      items:
        type: number
        nullable: true
```

上記の定義ファイルをgenerateすると、```(number | null)[]```となるはずが、次のような型が出力されてしまう。
```typescript
/* eslint-disable */
export type Example = number | null[]
```

【参考】
https://github.com/ID157/openapi2aspida-bugreport
- **Package version:**
  
  `v0.16.5`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v16.7.0`
- **npm version:**
  
  `7.20.3`

**Comment by hashue** [comment]
- Package version: `v0.16.5`
- OS: macOS
- Node.js version: `v16.13.0`
- npm version: `8.1.2`
において再現しませんでした。
可能であれば各種ツールのアップデートをお願いします

**Comment by hashue** [comment]
対応が遅れてしまって申し訳ありません。
最新バージョンでの再現確認しましたので、対処いたします。もうしばらくお待ちください

**Comment by hashue** [comment]
develpブランチにて対応しました

**Comment by ID157** [comment]
対応ありがとうございます🙇‍♂️

**Comment by hashue** [comment]
こちら、最新バージョン(v0.17.0)にて対応しています。issue報告ありがとうございました🙇‍♂️
