### ISSUE TITLE
`-o` option is not working.

### ISSUE THREAD

**Issue by cornerc** [aspida/openapi2aspida#247]
## Description

The `-o` option always results in output to `api/`.

```
npx openapi2aspida -i=path/to/spec.yml -o=lib/api/sample
```

## Environment

- **Package version:**
  
  `v0.23.1`
- **OS:**
  
  - [ ] Linux
  - [x] Windows
  - [x] macOS
- **Node.js version:**
  
  `v18.16.0`
- **npm version:**
  
  `9.5.1`

**Comment by solufa** [comment]
Fixed in v0.23.2
