### ISSUE TITLE
additional slash cause error

### ISSUE THREAD

**Issue by qiwang97** [aspida/openapi2aspida#77]
Openapi2aspida auto add slash like `const PATH0 = '/commodity/list'` but it causes ` 'input' must not begin with a slash when using 'prefixUrl' ` error when used with `ky`

Is there anyway to remove the prefix slash to `const PATH0 = 'commodity/list'` after generating apis?

**Comment by solufa** [comment]
Thanks for posting.

For the following reasons, I may stop updating aspida/ky.
- Cannot compile with tsc and development is too much work
- Low number of users (less than 10 users/day)

To resolve this issue, I need to fix aspida itself.
But I can not fix aspida for aspida/ky.

Sorry.
